<?php
/*
*  @Autor:        Michal Fujak
*  @version       2.0.150
*  @copyright     Michal Fujak - Programator
*  @framework     Enterprise 2.0
*  @license       http://www.dev-droid.sk
*  @this website  http://www.android.dev-droid.sk [ FruitShop webSite ]
*  @Copyring      10.09.2019 21:00
*  @File          controllers/Menu.php
*  @Update        edit:    [n/a][n/a]  version[n/a] [n/a]
*/

namespace controllers;

use language\sk\exception\ExceptionListVariable;
use model\driver\DriverConnect;
use model\sql\SqlManager;
use model\table\Tables;

class Menu extends MappingMenu
{
    /**
     * @variable
     */
    public $sql;
    public $result;
    public $row;

    /**
     * @object
     */
    public $objConn;
    public $objStmt;
    public $sqlManager;
    public $menu_cat;
    public $lang;
    public $objLang;

    // Construct starting MappingConstruct
    public function __construct()
    {
        parent::__construct();
        $this->objConn = new DriverConnect();
        $this->objStmt = $this->objConn->connectRealPDO();
        $this->sqlManager = new SqlManager(Tables::TABLE_MENU);
        $this->objLang = new ExceptionListVariable();
        $this->lang = array_merge($this->objLang->exceptionListMenu);
        $this->setLimitCategory(8);
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    /**
     * @getLoadMenuItems()
     * @return <array>
     */
    public function getLoadMenuItems()
    {
        // Method load category and items
        try
        {
            $this->sql = $this->sqlManager->getSelectTrim() .
                $this->sqlManager->getStarTrim() .
                $this->sqlManager->getFromTrim() .
                $this->sqlManager->table . " " .
                $this->sqlManager->getOrderByTrim() . self::$id .
                $this->sqlManager->getLimitTrim() . ":" . self::$menuLimit;
            $this->result = $this->objStmt->prepare($this->sql);
            //
            if(!$this->result)
            {
                print $this->lang['EXCEPTION_MENU_ERROR_MESSAGE_10010'];
            }
            $this->result->bindValue(":" . self::$menuLimit, self::getLimitCategory(), \PDO::PARAM_INT);
            $this->result->execute();
            $this->menu_cat = array();
            while($item = $this->result->fetch(\PDO::FETCH_ASSOC))
            {
                $this->menu_cat[] = $item;
            }
            return $this->menu_cat;
        }
        catch(\Exception $e)
        {
            print $this->lang['EXCEPTION_MENU_ERROR_MESSAGE_10012'];
        }
    }


}

?>
